
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.PrintStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.BadLocationException;

/*

Cześć Szymon, programujesz

 */

/**
 *
 * @author Szymoon
 */
public class Kalkulator extends javax.swing.JFrame {

    
    public Kalkulator() {
        int szer = (int) Toolkit.getDefaultToolkit().getScreenSize().getWidth();
        int wys = (int) Toolkit.getDefaultToolkit().getScreenSize().getHeight();
        this.setLocation((szer - this.getSize().width)/2, (wys - this.getSize().height)/2);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jedynka = new javax.swing.JButton();
        Dwójka = new javax.swing.JButton();
        Trójka = new javax.swing.JButton();
        Czwórka = new javax.swing.JButton();
        Piątka = new javax.swing.JButton();
        szóstka = new javax.swing.JButton();
        Dziewiątka = new javax.swing.JButton();
        siódemka = new javax.swing.JButton();
        Ósemka = new javax.swing.JButton();
        Odejmowanie = new javax.swing.JButton();
        Dodawanie = new javax.swing.JButton();
        Enter = new javax.swing.JButton();
        PoleTekstowe = new javax.swing.JTextField();
        Usuń = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Jedynka.setText("1");
        Jedynka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JedynkaActionPerformed(evt);
            }
        });

        Dwójka.setText("2");
        Dwójka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DwójkaActionPerformed(evt);
            }
        });

        Trójka.setText("3");
        Trójka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrójkaActionPerformed(evt);
            }
        });

        Czwórka.setText("4");
        Czwórka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CzwórkaActionPerformed(evt);
            }
        });

        Piątka.setText("5");
        Piątka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PiątkaActionPerformed(evt);
            }
        });

        szóstka.setText("6");
        szóstka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                szóstkaActionPerformed(evt);
            }
        });

        Dziewiątka.setText("9");
        Dziewiątka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DziewiątkaActionPerformed(evt);
            }
        });

        siódemka.setText("7");
        siódemka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siódemkaActionPerformed(evt);
            }
        });

        Ósemka.setText("8");
        Ósemka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ÓsemkaActionPerformed(evt);
            }
        });

        Odejmowanie.setText("-");
        Odejmowanie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OdejmowanieActionPerformed(evt);
            }
        });

        Dodawanie.setText("+");
        Dodawanie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DodawanieActionPerformed(evt);
            }
        });

        Enter.setText("Enter");
        Enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterActionPerformed(evt);
            }
        });

        Usuń.setText("Usuń");
        Usuń.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuńActionPerformed(evt);
            }
        });

        jButton1.setText("/");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PoleTekstowe)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Czwórka, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Piątka, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(szóstka, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Dodawanie, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(siódemka, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Ósemka, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Dziewiątka, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Enter)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Jedynka, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Dwójka, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Trójka, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Odejmowanie, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Usuń)))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Czwórka, Dodawanie, Dwójka, Dziewiątka, Enter, Jedynka, Odejmowanie, Piątka, Trójka, Usuń, jButton1, jButton2, siódemka, szóstka, Ósemka});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(PoleTekstowe, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jedynka)
                    .addComponent(Dwójka)
                    .addComponent(Trójka)
                    .addComponent(Odejmowanie)
                    .addComponent(Usuń))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Czwórka)
                    .addComponent(Piątka)
                    .addComponent(szóstka)
                    .addComponent(Dodawanie)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(siódemka)
                    .addComponent(Ósemka)
                    .addComponent(Dziewiątka)
                    .addComponent(Enter)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JedynkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JedynkaActionPerformed
        
        PoleTekstowe.setText(PoleTekstowe.getText()+"1");
    }//GEN-LAST:event_JedynkaActionPerformed

    private void DwójkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DwójkaActionPerformed
         
          PoleTekstowe.setText(PoleTekstowe.getText()+"2");
        
      
    }//GEN-LAST:event_DwójkaActionPerformed

    private void TrójkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrójkaActionPerformed
       PoleTekstowe.setText(PoleTekstowe.getText()+"3");
    }//GEN-LAST:event_TrójkaActionPerformed

    private void CzwórkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CzwórkaActionPerformed
    PoleTekstowe.setText(PoleTekstowe.getText()+"4");
    }//GEN-LAST:event_CzwórkaActionPerformed

    private void PiątkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PiątkaActionPerformed
PoleTekstowe.setText(PoleTekstowe.getText()+"5");
    }//GEN-LAST:event_PiątkaActionPerformed

    private void szóstkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_szóstkaActionPerformed
PoleTekstowe.setText(PoleTekstowe.getText()+"6");
    }//GEN-LAST:event_szóstkaActionPerformed

    private void siódemkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siódemkaActionPerformed
PoleTekstowe.setText(PoleTekstowe.getText()+"7");
    }//GEN-LAST:event_siódemkaActionPerformed

    private void ÓsemkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ÓsemkaActionPerformed
PoleTekstowe.setText(PoleTekstowe.getText()+"8");
    }//GEN-LAST:event_ÓsemkaActionPerformed

    private void DziewiątkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DziewiątkaActionPerformed
PoleTekstowe.setText(PoleTekstowe.getText()+"9");
    }//GEN-LAST:event_DziewiątkaActionPerformed

    private void UsuńActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuńActionPerformed

    int i = PoleTekstowe.getText().length() - 1;
    
   
    
    if(PoleTekstowe.getText().length()>0)
        try {
            PoleTekstowe.setText(PoleTekstowe.getText(0, i));
        } catch (BadLocationException ex) {
            Logger.getLogger(Kalkulator.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Błąd usuwania");
        }
    else if(PoleTekstowe.getText().length()<0)
    {
     Usuń.addKeyListener(new KeyAdapter() {
         public void keyPressed(KeyEvent ke) {
     ke.consume();
    }
});
    }

        
       

    }//GEN-LAST:event_UsuńActionPerformed

    private void OdejmowanieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OdejmowanieActionPerformed
     
        OdejmowanieHandler odejmowanie = new OdejmowanieHandler();
        odejmowanie.actionPerformed(evt);
//       Odejmowaniex2();
//        int długość = PoleTekstowe.getText().length();
//        System.out.println(długość);
//        PoleTekstowe.getText();
//     System.out.println(PobieranieDrugiejSekwencji(długość));
    }//GEN-LAST:event_OdejmowanieActionPerformed
   int długośćsek;

    private void setLocation() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    class OdejmowanieHandler implements ActionListener
            {

        public OdejmowanieHandler() 
        {
         int długość = PoleTekstowe.getText().length() ;
         długośćsek = długość;
        }

        @Override
        public void actionPerformed(ActionEvent ae) {
            PoleTekstowe.setText(PoleTekstowe.getText()+ "-" );
        }
            
            }
    
    class DodawanieHandler implements ActionListener
            {

        public DodawanieHandler() 
        {
         int długość = PoleTekstowe.getText().length() ;
         długośćsek = długość;
        }

        @Override
        public void actionPerformed(ActionEvent ae) {
            PoleTekstowe.setText(PoleTekstowe.getText()+ "+" );
        }
            
            }
    
     class DzielenieHandler implements ActionListener
            {

        public DzielenieHandler() 
        {
         int długość = PoleTekstowe.getText().length() ;
         długośćsek = długość;
        }

        @Override
        public void actionPerformed(ActionEvent ae) {
            PoleTekstowe.setText(PoleTekstowe.getText()+ "/" );
        }
            
            }
    
    private void EnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterActionPerformed
        
        try {                                      
            
            try {
                System.out.println("Znak dodawania czy odejmowania :" +PoleTekstowe.getText(długośćsek,1));
            } catch (BadLocationException ex) {
                Logger.getLogger(Kalkulator.class.getName()).log(Level.SEVERE, null, ex);
            }
            
           
            if(PoleTekstowe.getText(długośćsek, 1).equals("-"))
            {
                System.out.println("WYKONUJEMY METODE ODEJMOWANIA");

                try {
                    String tekst = null;
                    try {
                        
                        tekst = PoleTekstowe.getText(0,długośćsek);
                        System.out.println("Odejmowanie długość sek " +tekst);
                    } catch (BadLocationException ex) {
                        Logger.getLogger(Kalkulator.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    int coś = Integer.valueOf(tekst);
                    System.out.println(coś);
                    int sekwecnja =PoleTekstowe.getText().length();
                    System.out.println("sekwencja: " + sekwecnja);
                    int przesłany = (sekwecnja - długośćsek)-1;
                    
                    String nazwa2 =PoleTekstowe.getText(długośćsek+1,przesłany );
                    
                    int coś2 = Integer.valueOf(nazwa2);
                    
                    int wynik =coś - coś2;
                    String wynik2 = String.valueOf(wynik);
                    System.out.println("To jest wynik:" + wynik2);
                    PoleTekstowe.setText(wynik2);
                } catch (BadLocationException ex) {
                    Logger.getLogger(Kalkulator.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
             if(PoleTekstowe.getText(długośćsek, 1).equals("+"))
            
            {
                String tekst = null;
                try {
                    tekst = PoleTekstowe.getText(0,długośćsek);
                    
                    System.out.println("Dodawanie pierwsza sekewcnja :"+ tekst);
                } catch (BadLocationException ex) {
                    Logger.getLogger(Kalkulator.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                int coś = Integer.valueOf(tekst);
                System.out.println("coś mordo"+coś);
                int sekwecnja =PoleTekstowe.getText().length();
                System.out.println("sekwencja: " + sekwecnja);
                int przesłany = (sekwecnja - długośćsek)-1;
             
                String nazwa2 = null;
                try {
                    nazwa2 = PoleTekstowe.getText(długośćsek+1,przesłany );
                } catch (BadLocationException ex) {
                    Logger.getLogger(Kalkulator.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                int coś2 = Integer.valueOf(nazwa2);
                
                int wynik =coś + coś2;
                String wynik2 = String.valueOf(wynik);
                System.out.println("To jest wynik:" + wynik2);
                PoleTekstowe.setText(wynik2);
            }
            if(PoleTekstowe.getText(długośćsek, 1).equals("/"))
            {
            String tekst = null;
                try {
                    tekst = PoleTekstowe.getText(0,długośćsek);
                    
                    System.out.println("Dodawanie pierwsza sekewcnja :"+ tekst);
                } catch (BadLocationException ex) {
                    Logger.getLogger(Kalkulator.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                int coś = Integer.valueOf(tekst);
                System.out.println("coś mordo"+coś);
                int sekwecnja =PoleTekstowe.getText().length();
                System.out.println("sekwencja: " + sekwecnja);
                int przesłany = (sekwecnja - długośćsek)-1;
             
                String nazwa2 = null;
                try {
                    nazwa2 = PoleTekstowe.getText(długośćsek+1,przesłany );
                } catch (BadLocationException ex) {
                    Logger.getLogger(Kalkulator.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                int coś2 = Integer.valueOf(nazwa2);
                
                int wynik =coś / coś2;
                String wynik2 = String.valueOf(wynik);
                System.out.println("To jest wynik:" + wynik2);
                PoleTekstowe.setText(wynik2);
            
            
            }
            
        } catch (BadLocationException ex) {
            Logger.getLogger(Kalkulator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EnterActionPerformed

    private void DodawanieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DodawanieActionPerformed
       DodawanieHandler dodawanie = new DodawanieHandler();
        dodawanie.actionPerformed(evt);
    }//GEN-LAST:event_DodawanieActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       DzielenieHandler dzielenie = new DzielenieHandler();
       dzielenie.actionPerformed(evt);
                
    }//GEN-LAST:event_jButton1ActionPerformed

    public int Odejmowaniex2()
    {
    int a = PobieraniePierwszejSekwencji();
        PoleTekstowe.setText(PoleTekstowe.getText()+ "-" );
   int długość = PoleTekstowe.getText().length() -1;
        return długość;
    }
    
    public int PobieraniePierwszejSekwencji()
    {
    
        String tekst = PoleTekstowe.getText();
        int liczba = Integer.valueOf(tekst);
        return liczba;
    
    }
    
    public int PobieranieDrugiejSekwencji(int dłguość) throws BadLocationException
    {
    String nazwa = PoleTekstowe.getText(dłguość, 5);
    int liczba = Integer.valueOf(nazwa);
    return liczba;
    
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Czwórka;
    private javax.swing.JButton Dodawanie;
    private javax.swing.JButton Dwójka;
    private javax.swing.JButton Dziewiątka;
    private javax.swing.JButton Enter;
    private javax.swing.JButton Jedynka;
    private javax.swing.JButton Odejmowanie;
    private javax.swing.JButton Piątka;
    private javax.swing.JTextField PoleTekstowe;
    private javax.swing.JButton Trójka;
    private javax.swing.JButton Usuń;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton siódemka;
    private javax.swing.JButton szóstka;
    private javax.swing.JButton Ósemka;
    // End of variables declaration//GEN-END:variables
}
